[package]
name = "ctrlsys"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"
slugify = "0.1.0"

[dependencies.uuid]
version = "1.5.0"
features = ["v4", "fast-rng", "macro-diagnostics", "serde"]
