apiVersion: v1
kind: ServiceAccount
metadata:
  name: jobscheduler
  labels:
    app: jobscheduler
    component: scheduler

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jobscheduler
  labels:
    app: jobscheduler
    component: scheduler
rules:
# Jobs management
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs/status"]
  verbs: ["get", "list", "watch"]

# Pods read access (for job status monitoring)
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]

# Events read access (for debugging)
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]

# Namespaces read access
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jobscheduler
  labels:
    app: jobscheduler
    component: scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jobscheduler
subjects:
- kind: ServiceAccount
  name: jobscheduler
  namespace: default