apiVersion: v1
kind: Service
metadata:
  name: jobscheduler
  labels:
    app: jobscheduler
    component: scheduler
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 50054
    targetPort: grpc
    protocol: TCP
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  selector:
    app: jobscheduler