# CLI Tool Tasks

version: '3'

vars:
  CLI_NAME: ctrlsys
  INSTALL_PATH: '{{.INSTALL_PATH | default "~/.local/bin"}}'

tasks:
  # Build tasks
  build:
    desc: "🏗️ Build CLI tool"
    cmds:
      - cargo build

  build:release:
    desc: "🏗️ Build CLI tool (release)"
    cmds:
      - cargo build --release

  # Test tasks
  test:
    desc: "🧪 Run CLI tests"
    cmds:
      - cargo test

  test:integration:
    desc: "🧪 Run CLI integration tests"
    cmds:
      - cargo test --test integration

  # Code quality
  fmt:
    desc: "🎨 Format CLI code"
    cmds:
      - cargo fmt

  clippy:
    desc: "🔍 Run clippy on CLI"
    cmds:
      - cargo clippy -- -D warnings

  check:
    desc: "✅ Check CLI (fmt + clippy + test)"
    cmds:
      - task: fmt
      - task: clippy
      - task: test

  # Development
  run:
    desc: "▶️ Run CLI tool"
    cmds:
      - cargo run -- {{.CLI_ARGS}}

  run:help:
    desc: "❓ Show CLI help"
    cmds:
      - cargo run -- --help

  watch:
    desc: "👀 Watch and rebuild CLI"
    cmds:
      - cargo watch -x build

  watch:test:
    desc: "👀 Watch and test CLI"
    cmds:
      - cargo watch -x test

  # Installation
  install:
    desc: "📦 Install CLI tool locally"
    cmds:
      - cargo install --path .

  install:path:
    desc: "📦 Install CLI to specific path"
    cmds:
      - cargo install --path . --root {{.INSTALL_PATH}}

  uninstall:
    desc: "🗑️ Uninstall CLI tool"
    cmds:
      - cargo uninstall {{.CLI_NAME}}

  # Distribution
  dist:
    desc: "📦 Build distribution binaries"
    cmds:
      - cargo build --release
      - mkdir -p dist/
      - cp target/release/{{.CLI_NAME}} dist/{{.CLI_NAME}}-{{OS}}-{{ARCH}}

  dist:all:
    desc: "📦 Build for all targets"
    cmds:
      - cargo build --release --target x86_64-unknown-linux-gnu
      - cargo build --release --target x86_64-apple-darwin
      - cargo build --release --target aarch64-apple-darwin
      - mkdir -p dist/
      - cp target/x86_64-unknown-linux-gnu/release/{{.CLI_NAME}} dist/{{.CLI_NAME}}-linux-amd64
      - cp target/x86_64-apple-darwin/release/{{.CLI_NAME}} dist/{{.CLI_NAME}}-darwin-amd64
      - cp target/aarch64-apple-darwin/release/{{.CLI_NAME}} dist/{{.CLI_NAME}}-darwin-arm64

  # Documentation
  docs:
    desc: "📚 Generate CLI documentation"
    cmds:
      - cargo doc --open

  man:
    desc: "📖 Generate man pages"
    cmds:
      - cargo run -- --generate-man > docs/{{.CLI_NAME}}.1

  # Cleanup
  clean:
    desc: "🧹 Clean CLI build artifacts"
    cmds:
      - cargo clean
      - rm -rf target/ dist/

  # Development shortcuts
  dev:
    desc: "🚀 Quick development cycle"
    cmds:
      - task: check
      - task: run:help