apiVersion: batch/v1
kind: Job
metadata:
  name: timer-job-example
  labels:
    app: timer-service
    version: v1
spec:
  backoffLimit: 3
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: timer-service
        version: v1
    spec:
      restartPolicy: Never
      containers:
      - name: timer
        image: ghcr.io/t-eckert/ctrlsys/timer:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: TIMER_DURATION_SECONDS
          value: "300"
        - name: TIMER_NAME
          value: "build-timeout"
        - name: CONTROL_PLANE_ENDPOINT
          value: "http://control-plane-service:50053"
        - name: TIMER_LABELS
          value: '{"environment":"prod","team":"platform"}'
        - name: RUST_LOG
          value: "info"
        - name: GRPC_PORT
          value: "50051"
        ports:
        - containerPort: 50051
          name: grpc
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
            - timer-service
            - health
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - timer-service
            - health
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
