// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/jobscheduler.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_PENDING     JobStatus = 1
	JobStatus_JOB_STATUS_RUNNING     JobStatus = 2
	JobStatus_JOB_STATUS_SUCCEEDED   JobStatus = 3
	JobStatus_JOB_STATUS_FAILED      JobStatus = 4
	JobStatus_JOB_STATUS_CANCELLED   JobStatus = 5
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_PENDING",
		2: "JOB_STATUS_RUNNING",
		3: "JOB_STATUS_SUCCEEDED",
		4: "JOB_STATUS_FAILED",
		5: "JOB_STATUS_CANCELLED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_PENDING":     1,
		"JOB_STATUS_RUNNING":     2,
		"JOB_STATUS_SUCCEEDED":   3,
		"JOB_STATUS_FAILED":      4,
		"JOB_STATUS_CANCELLED":   5,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_jobscheduler_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_proto_jobscheduler_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_jobscheduler_proto_rawDescGZIP(), []int{0}
}

type ScheduleJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the job (optional, will be generated if not provided)
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Human-readable name for the job
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Job type and configuration
	//
	// Types that are valid to be assigned to JobConfig:
	//
	//	*ScheduleJobRequest_TimerJob
	JobConfig isScheduleJobRequest_JobConfig `protobuf_oneof:"job_config"`
	// Optional labels for the job
	Labels map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional annotations for the job
	Annotations map[string]string `protobuf:"bytes,4,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Resource requirements
	Resources *ResourceRequirements `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"`
	// Optional namespace (defaults to default)
	Namespace string `protobuf:"bytes,6,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Optional created_by field
	CreatedBy     string `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleJobRequest) Reset() {
	*x = ScheduleJobRequest{}
	mi := &file_proto_jobscheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleJobRequest) ProtoMessage() {}

func (x *ScheduleJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jobscheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleJobRequest.ProtoReflect.Descriptor instead.
func (*ScheduleJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_jobscheduler_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduleJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ScheduleJobRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScheduleJobRequest) GetJobConfig() isScheduleJobRequest_JobConfig {
	if x != nil {
		return x.JobConfig
	}
	return nil
}

func (x *ScheduleJobRequest) GetTimerJob() *TimerJobConfig {
	if x != nil {
		if x, ok := x.JobConfig.(*ScheduleJobRequest_TimerJob); ok {
			return x.TimerJob
		}
	}
	return nil
}

func (x *ScheduleJobRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ScheduleJobRequest) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ScheduleJobRequest) GetResources() *ResourceRequirements {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ScheduleJobRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ScheduleJobRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type isScheduleJobRequest_JobConfig interface {
	isScheduleJobRequest_JobConfig()
}

type ScheduleJobRequest_TimerJob struct {
	TimerJob *TimerJobConfig `protobuf:"bytes,10,opt,name=timer_job,json=timerJob,proto3,oneof"`
}

func (*ScheduleJobRequest_TimerJob) isScheduleJobRequest_JobConfig() {}

type ScheduleJobResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the scheduled job
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Status of the scheduling operation
	Status JobStatus `protobuf:"varint,2,opt,name=status,proto3,enum=jobscheduler.JobStatus" json:"status,omitempty"`
	// Human-readable message
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Kubernetes job name that was created
	K8SJobName    string `protobuf:"bytes,4,opt,name=k8s_job_name,json=k8sJobName,proto3" json:"k8s_job_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleJobResponse) Reset() {
	*x = ScheduleJobResponse{}
	mi := &file_proto_jobscheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleJobResponse) ProtoMessage() {}

func (x *ScheduleJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jobscheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleJobResponse.ProtoReflect.Descriptor instead.
func (*ScheduleJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_jobscheduler_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduleJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ScheduleJobResponse) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *ScheduleJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ScheduleJobResponse) GetK8SJobName() string {
	if x != nil {
		return x.K8SJobName
	}
	return ""
}

type GetJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_proto_jobscheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jobscheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_jobscheduler_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobInfo       *JobInfo               `protobuf:"bytes,2,opt,name=job_info,json=jobInfo,proto3" json:"job_info,omitempty"`
	Status        JobStatus              `protobuf:"varint,3,opt,name=status,proto3,enum=jobscheduler.JobStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusResponse) Reset() {
	*x = GetJobStatusResponse{}
	mi := &file_proto_jobscheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusResponse) ProtoMessage() {}

func (x *GetJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jobscheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_jobscheduler_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetJobStatusResponse) GetJobInfo() *JobInfo {
	if x != nil {
		return x.JobInfo
	}
	return nil
}

func (x *GetJobStatusResponse) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *GetJobStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListJobsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional label selector
	LabelSelector map[string]string `protobuf:"bytes,1,rep,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional namespace filter
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Optional status filter
	StatusFilter []JobStatus `protobuf:"varint,3,rep,packed,name=status_filter,json=statusFilter,proto3,enum=jobscheduler.JobStatus" json:"status_filter,omitempty"`
	// Pagination
	PageSize      int32  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_proto_jobscheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jobscheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_proto_jobscheduler_proto_rawDescGZIP(), []int{4}
}

func (x *ListJobsRequest) GetLabelSelector() map[string]string {
	if x != nil {
		return x.LabelSelector
	}
	return nil
}

func (x *ListJobsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListJobsRequest) GetStatusFilter() []JobStatus {
	if x != nil {
		return x.StatusFilter
	}
	return nil
}

func (x *ListJobsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListJobsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobInfo             `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_proto_jobscheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jobscheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_proto_jobscheduler_proto_rawDescGZIP(), []int{5}
}

func (x *ListJobsResponse) GetJobs() []*JobInfo {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListJobsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListJobsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_proto_jobscheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jobscheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_jobscheduler_proto_rawDescGZIP(), []int{6}
}

func (x *CancelJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_proto_jobscheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jobscheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_jobscheduler_proto_rawDescGZIP(), []int{7}
}

func (x *CancelJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Job configuration for Timer jobs
type TimerJobConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Duration in seconds for the timer
	DurationSeconds int64 `protobuf:"varint,1,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	// Timer name
	TimerName string `protobuf:"bytes,2,opt,name=timer_name,json=timerName,proto3" json:"timer_name,omitempty"`
	// Control plane endpoint for reporting completion
	ControlPlaneEndpoint string `protobuf:"bytes,3,opt,name=control_plane_endpoint,json=controlPlaneEndpoint,proto3" json:"control_plane_endpoint,omitempty"`
	// Container image to use (optional, defaults to configured image)
	Image string `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	// Log level for the timer service
	LogLevel string `protobuf:"bytes,5,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	// Additional environment variables
	Env           map[string]string `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimerJobConfig) Reset() {
	*x = TimerJobConfig{}
	mi := &file_proto_jobscheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimerJobConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerJobConfig) ProtoMessage() {}

func (x *TimerJobConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jobscheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerJobConfig.ProtoReflect.Descriptor instead.
func (*TimerJobConfig) Descriptor() ([]byte, []int) {
	return file_proto_jobscheduler_proto_rawDescGZIP(), []int{8}
}

func (x *TimerJobConfig) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *TimerJobConfig) GetTimerName() string {
	if x != nil {
		return x.TimerName
	}
	return ""
}

func (x *TimerJobConfig) GetControlPlaneEndpoint() string {
	if x != nil {
		return x.ControlPlaneEndpoint
	}
	return ""
}

func (x *TimerJobConfig) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *TimerJobConfig) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *TimerJobConfig) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

// Resource requirements for jobs
type ResourceRequirements struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      *ResourceList          `protobuf:"bytes,1,opt,name=requests,proto3" json:"requests,omitempty"`
	Limits        *ResourceList          `protobuf:"bytes,2,opt,name=limits,proto3" json:"limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequirements) Reset() {
	*x = ResourceRequirements{}
	mi := &file_proto_jobscheduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequirements) ProtoMessage() {}

func (x *ResourceRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jobscheduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequirements.ProtoReflect.Descriptor instead.
func (*ResourceRequirements) Descriptor() ([]byte, []int) {
	return file_proto_jobscheduler_proto_rawDescGZIP(), []int{9}
}

func (x *ResourceRequirements) GetRequests() *ResourceList {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *ResourceRequirements) GetLimits() *ResourceList {
	if x != nil {
		return x.Limits
	}
	return nil
}

type ResourceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           string                 `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        string                 `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Storage       string                 `protobuf:"bytes,3,opt,name=storage,proto3" json:"storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceList) Reset() {
	*x = ResourceList{}
	mi := &file_proto_jobscheduler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceList) ProtoMessage() {}

func (x *ResourceList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jobscheduler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceList.ProtoReflect.Descriptor instead.
func (*ResourceList) Descriptor() ([]byte, []int) {
	return file_proto_jobscheduler_proto_rawDescGZIP(), []int{10}
}

func (x *ResourceList) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *ResourceList) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *ResourceList) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

// Job information
type JobInfo struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	JobId       string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	K8SJobName  string                 `protobuf:"bytes,3,opt,name=k8s_job_name,json=k8sJobName,proto3" json:"k8s_job_name,omitempty"`
	Namespace   string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Status      JobStatus              `protobuf:"varint,5,opt,name=status,proto3,enum=jobscheduler.JobStatus" json:"status,omitempty"`
	CreatedAt   int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt   int64                  `protobuf:"varint,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt int64                  `protobuf:"varint,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	CreatedBy   string                 `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Labels      map[string]string      `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations map[string]string      `protobuf:"bytes,11,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Job type specific information
	//
	// Types that are valid to be assigned to JobDetails:
	//
	//	*JobInfo_TimerDetails
	JobDetails    isJobInfo_JobDetails `protobuf_oneof:"job_details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobInfo) Reset() {
	*x = JobInfo{}
	mi := &file_proto_jobscheduler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobInfo) ProtoMessage() {}

func (x *JobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jobscheduler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobInfo.ProtoReflect.Descriptor instead.
func (*JobInfo) Descriptor() ([]byte, []int) {
	return file_proto_jobscheduler_proto_rawDescGZIP(), []int{11}
}

func (x *JobInfo) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JobInfo) GetK8SJobName() string {
	if x != nil {
		return x.K8SJobName
	}
	return ""
}

func (x *JobInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *JobInfo) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *JobInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *JobInfo) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *JobInfo) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *JobInfo) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *JobInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *JobInfo) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *JobInfo) GetJobDetails() isJobInfo_JobDetails {
	if x != nil {
		return x.JobDetails
	}
	return nil
}

func (x *JobInfo) GetTimerDetails() *TimerJobDetails {
	if x != nil {
		if x, ok := x.JobDetails.(*JobInfo_TimerDetails); ok {
			return x.TimerDetails
		}
	}
	return nil
}

type isJobInfo_JobDetails interface {
	isJobInfo_JobDetails()
}

type JobInfo_TimerDetails struct {
	TimerDetails *TimerJobDetails `protobuf:"bytes,20,opt,name=timer_details,json=timerDetails,proto3,oneof"`
}

func (*JobInfo_TimerDetails) isJobInfo_JobDetails() {}

type TimerJobDetails struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DurationSeconds      int64                  `protobuf:"varint,1,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	TimerName            string                 `protobuf:"bytes,2,opt,name=timer_name,json=timerName,proto3" json:"timer_name,omitempty"`
	ControlPlaneEndpoint string                 `protobuf:"bytes,3,opt,name=control_plane_endpoint,json=controlPlaneEndpoint,proto3" json:"control_plane_endpoint,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TimerJobDetails) Reset() {
	*x = TimerJobDetails{}
	mi := &file_proto_jobscheduler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimerJobDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerJobDetails) ProtoMessage() {}

func (x *TimerJobDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jobscheduler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerJobDetails.ProtoReflect.Descriptor instead.
func (*TimerJobDetails) Descriptor() ([]byte, []int) {
	return file_proto_jobscheduler_proto_rawDescGZIP(), []int{12}
}

func (x *TimerJobDetails) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *TimerJobDetails) GetTimerName() string {
	if x != nil {
		return x.TimerName
	}
	return ""
}

func (x *TimerJobDetails) GetControlPlaneEndpoint() string {
	if x != nil {
		return x.ControlPlaneEndpoint
	}
	return ""
}

var File_proto_jobscheduler_proto protoreflect.FileDescriptor

const file_proto_jobscheduler_proto_rawDesc = "" +
	"\n" +
	"\x18proto/jobscheduler.proto\x12\fjobscheduler\"\x9f\x04\n" +
	"\x12ScheduleJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12;\n" +
	"\ttimer_job\x18\n" +
	" \x01(\v2\x1c.jobscheduler.TimerJobConfigH\x00R\btimerJob\x12D\n" +
	"\x06labels\x18\x03 \x03(\v2,.jobscheduler.ScheduleJobRequest.LabelsEntryR\x06labels\x12S\n" +
	"\vannotations\x18\x04 \x03(\v21.jobscheduler.ScheduleJobRequest.AnnotationsEntryR\vannotations\x12@\n" +
	"\tresources\x18\x05 \x01(\v2\".jobscheduler.ResourceRequirementsR\tresources\x12\x1c\n" +
	"\tnamespace\x18\x06 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\tR\tcreatedBy\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"job_config\"\x99\x01\n" +
	"\x13ScheduleJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.jobscheduler.JobStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12 \n" +
	"\fk8s_job_name\x18\x04 \x01(\tR\n" +
	"k8sJobName\",\n" +
	"\x13GetJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xaa\x01\n" +
	"\x14GetJobStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x120\n" +
	"\bjob_info\x18\x02 \x01(\v2\x15.jobscheduler.JobInfoR\ajobInfo\x12/\n" +
	"\x06status\x18\x03 \x01(\x0e2\x17.jobscheduler.JobStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xc4\x02\n" +
	"\x0fListJobsRequest\x12W\n" +
	"\x0elabel_selector\x18\x01 \x03(\v20.jobscheduler.ListJobsRequest.LabelSelectorEntryR\rlabelSelector\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12<\n" +
	"\rstatus_filter\x18\x03 \x03(\x0e2\x17.jobscheduler.JobStatusR\fstatusFilter\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\x1a@\n" +
	"\x12LabelSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x01\n" +
	"\x10ListJobsResponse\x12)\n" +
	"\x04jobs\x18\x01 \x03(\v2\x15.jobscheduler.JobInfoR\x04jobs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\")\n" +
	"\x10CancelJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"G\n" +
	"\x11CancelJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb4\x02\n" +
	"\x0eTimerJobConfig\x12)\n" +
	"\x10duration_seconds\x18\x01 \x01(\x03R\x0fdurationSeconds\x12\x1d\n" +
	"\n" +
	"timer_name\x18\x02 \x01(\tR\ttimerName\x124\n" +
	"\x16control_plane_endpoint\x18\x03 \x01(\tR\x14controlPlaneEndpoint\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x1b\n" +
	"\tlog_level\x18\x05 \x01(\tR\blogLevel\x127\n" +
	"\x03env\x18\x06 \x03(\v2%.jobscheduler.TimerJobConfig.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x01\n" +
	"\x14ResourceRequirements\x126\n" +
	"\brequests\x18\x01 \x01(\v2\x1a.jobscheduler.ResourceListR\brequests\x122\n" +
	"\x06limits\x18\x02 \x01(\v2\x1a.jobscheduler.ResourceListR\x06limits\"R\n" +
	"\fResourceList\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\tR\x06memory\x12\x18\n" +
	"\astorage\x18\x03 \x01(\tR\astorage\"\xfa\x04\n" +
	"\aJobInfo\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\fk8s_job_name\x18\x03 \x01(\tR\n" +
	"k8sJobName\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12/\n" +
	"\x06status\x18\x05 \x01(\x0e2\x17.jobscheduler.JobStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\a \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\b \x01(\x03R\vcompletedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\tR\tcreatedBy\x129\n" +
	"\x06labels\x18\n" +
	" \x03(\v2!.jobscheduler.JobInfo.LabelsEntryR\x06labels\x12H\n" +
	"\vannotations\x18\v \x03(\v2&.jobscheduler.JobInfo.AnnotationsEntryR\vannotations\x12D\n" +
	"\rtimer_details\x18\x14 \x01(\v2\x1d.jobscheduler.TimerJobDetailsH\x00R\ftimerDetails\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\r\n" +
	"\vjob_details\"\x91\x01\n" +
	"\x0fTimerJobDetails\x12)\n" +
	"\x10duration_seconds\x18\x01 \x01(\x03R\x0fdurationSeconds\x12\x1d\n" +
	"\n" +
	"timer_name\x18\x02 \x01(\tR\ttimerName\x124\n" +
	"\x16control_plane_endpoint\x18\x03 \x01(\tR\x14controlPlaneEndpoint*\xa2\x01\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_PENDING\x10\x01\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x02\x12\x18\n" +
	"\x14JOB_STATUS_SUCCEEDED\x10\x03\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x04\x12\x18\n" +
	"\x14JOB_STATUS_CANCELLED\x10\x052\xd2\x02\n" +
	"\fJobScheduler\x12R\n" +
	"\vScheduleJob\x12 .jobscheduler.ScheduleJobRequest\x1a!.jobscheduler.ScheduleJobResponse\x12U\n" +
	"\fGetJobStatus\x12!.jobscheduler.GetJobStatusRequest\x1a\".jobscheduler.GetJobStatusResponse\x12I\n" +
	"\bListJobs\x12\x1d.jobscheduler.ListJobsRequest\x1a\x1e.jobscheduler.ListJobsResponse\x12L\n" +
	"\tCancelJob\x12\x1e.jobscheduler.CancelJobRequest\x1a\x1f.jobscheduler.CancelJobResponseB9Z7github.com/t-eckert/ctrlsys/services/jobscheduler/protob\x06proto3"

var (
	file_proto_jobscheduler_proto_rawDescOnce sync.Once
	file_proto_jobscheduler_proto_rawDescData []byte
)

func file_proto_jobscheduler_proto_rawDescGZIP() []byte {
	file_proto_jobscheduler_proto_rawDescOnce.Do(func() {
		file_proto_jobscheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_jobscheduler_proto_rawDesc), len(file_proto_jobscheduler_proto_rawDesc)))
	})
	return file_proto_jobscheduler_proto_rawDescData
}

var file_proto_jobscheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_jobscheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_jobscheduler_proto_goTypes = []any{
	(JobStatus)(0),               // 0: jobscheduler.JobStatus
	(*ScheduleJobRequest)(nil),   // 1: jobscheduler.ScheduleJobRequest
	(*ScheduleJobResponse)(nil),  // 2: jobscheduler.ScheduleJobResponse
	(*GetJobStatusRequest)(nil),  // 3: jobscheduler.GetJobStatusRequest
	(*GetJobStatusResponse)(nil), // 4: jobscheduler.GetJobStatusResponse
	(*ListJobsRequest)(nil),      // 5: jobscheduler.ListJobsRequest
	(*ListJobsResponse)(nil),     // 6: jobscheduler.ListJobsResponse
	(*CancelJobRequest)(nil),     // 7: jobscheduler.CancelJobRequest
	(*CancelJobResponse)(nil),    // 8: jobscheduler.CancelJobResponse
	(*TimerJobConfig)(nil),       // 9: jobscheduler.TimerJobConfig
	(*ResourceRequirements)(nil), // 10: jobscheduler.ResourceRequirements
	(*ResourceList)(nil),         // 11: jobscheduler.ResourceList
	(*JobInfo)(nil),              // 12: jobscheduler.JobInfo
	(*TimerJobDetails)(nil),      // 13: jobscheduler.TimerJobDetails
	nil,                          // 14: jobscheduler.ScheduleJobRequest.LabelsEntry
	nil,                          // 15: jobscheduler.ScheduleJobRequest.AnnotationsEntry
	nil,                          // 16: jobscheduler.ListJobsRequest.LabelSelectorEntry
	nil,                          // 17: jobscheduler.TimerJobConfig.EnvEntry
	nil,                          // 18: jobscheduler.JobInfo.LabelsEntry
	nil,                          // 19: jobscheduler.JobInfo.AnnotationsEntry
}
var file_proto_jobscheduler_proto_depIdxs = []int32{
	9,  // 0: jobscheduler.ScheduleJobRequest.timer_job:type_name -> jobscheduler.TimerJobConfig
	14, // 1: jobscheduler.ScheduleJobRequest.labels:type_name -> jobscheduler.ScheduleJobRequest.LabelsEntry
	15, // 2: jobscheduler.ScheduleJobRequest.annotations:type_name -> jobscheduler.ScheduleJobRequest.AnnotationsEntry
	10, // 3: jobscheduler.ScheduleJobRequest.resources:type_name -> jobscheduler.ResourceRequirements
	0,  // 4: jobscheduler.ScheduleJobResponse.status:type_name -> jobscheduler.JobStatus
	12, // 5: jobscheduler.GetJobStatusResponse.job_info:type_name -> jobscheduler.JobInfo
	0,  // 6: jobscheduler.GetJobStatusResponse.status:type_name -> jobscheduler.JobStatus
	16, // 7: jobscheduler.ListJobsRequest.label_selector:type_name -> jobscheduler.ListJobsRequest.LabelSelectorEntry
	0,  // 8: jobscheduler.ListJobsRequest.status_filter:type_name -> jobscheduler.JobStatus
	12, // 9: jobscheduler.ListJobsResponse.jobs:type_name -> jobscheduler.JobInfo
	17, // 10: jobscheduler.TimerJobConfig.env:type_name -> jobscheduler.TimerJobConfig.EnvEntry
	11, // 11: jobscheduler.ResourceRequirements.requests:type_name -> jobscheduler.ResourceList
	11, // 12: jobscheduler.ResourceRequirements.limits:type_name -> jobscheduler.ResourceList
	0,  // 13: jobscheduler.JobInfo.status:type_name -> jobscheduler.JobStatus
	18, // 14: jobscheduler.JobInfo.labels:type_name -> jobscheduler.JobInfo.LabelsEntry
	19, // 15: jobscheduler.JobInfo.annotations:type_name -> jobscheduler.JobInfo.AnnotationsEntry
	13, // 16: jobscheduler.JobInfo.timer_details:type_name -> jobscheduler.TimerJobDetails
	1,  // 17: jobscheduler.JobScheduler.ScheduleJob:input_type -> jobscheduler.ScheduleJobRequest
	3,  // 18: jobscheduler.JobScheduler.GetJobStatus:input_type -> jobscheduler.GetJobStatusRequest
	5,  // 19: jobscheduler.JobScheduler.ListJobs:input_type -> jobscheduler.ListJobsRequest
	7,  // 20: jobscheduler.JobScheduler.CancelJob:input_type -> jobscheduler.CancelJobRequest
	2,  // 21: jobscheduler.JobScheduler.ScheduleJob:output_type -> jobscheduler.ScheduleJobResponse
	4,  // 22: jobscheduler.JobScheduler.GetJobStatus:output_type -> jobscheduler.GetJobStatusResponse
	6,  // 23: jobscheduler.JobScheduler.ListJobs:output_type -> jobscheduler.ListJobsResponse
	8,  // 24: jobscheduler.JobScheduler.CancelJob:output_type -> jobscheduler.CancelJobResponse
	21, // [21:25] is the sub-list for method output_type
	17, // [17:21] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_jobscheduler_proto_init() }
func file_proto_jobscheduler_proto_init() {
	if File_proto_jobscheduler_proto != nil {
		return
	}
	file_proto_jobscheduler_proto_msgTypes[0].OneofWrappers = []any{
		(*ScheduleJobRequest_TimerJob)(nil),
	}
	file_proto_jobscheduler_proto_msgTypes[11].OneofWrappers = []any{
		(*JobInfo_TimerDetails)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_jobscheduler_proto_rawDesc), len(file_proto_jobscheduler_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_jobscheduler_proto_goTypes,
		DependencyIndexes: file_proto_jobscheduler_proto_depIdxs,
		EnumInfos:         file_proto_jobscheduler_proto_enumTypes,
		MessageInfos:      file_proto_jobscheduler_proto_msgTypes,
	}.Build()
	File_proto_jobscheduler_proto = out.File
	file_proto_jobscheduler_proto_goTypes = nil
	file_proto_jobscheduler_proto_depIdxs = nil
}
